# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Get dependencies
      run: >-
        sudo apt-get update &&
        sudo apt-get install
        bc
        gcc
        libgl1-mesa-dev
        libwayland-dev
        libx11-dev
        libxkbcommon-dev
        xorg-dev
        xvfb
        language-pack-en
      if: ${{ runner.os == 'Linux' }}

    - name: Set environment variable LANG
      run: export LANG=en_EN.UTF-8
      if: ${{ runner.os == 'Linux' }}

    - name: Build
      run: go build -v main.go

    - name: Test
      run: go test -v ./...
